${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_add_tag_nm_/_add_tag_nm_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_all_man_files_/_all_man_files_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_bash_/_bash_/_man/arrays.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_bash_/_bash_/_man/conditions.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_bash_/_bash_/_man/constants.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_bash_/_bash_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_bash_/_bash_/_man/paradigm.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_bash_/_bash_/_man/parameters.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_cat_/_cat_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_ch_fn_ex_/_ch_fn_ex_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_choice_tag/_choice_tag/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_choice_tag_file/_choice_tag_file/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_edit_/_edit_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_f_f_/_f_f_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_f_f_/_f_f_/_tml/_00000/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_fs_/_fs_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_grep_/_grep_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_magic_nm_/_magic_nm_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_man_is/_man_is/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_menu_nm_/_menu_nm_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_mmenu_/_mmenu_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_pp_/_pp_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_ques_/_ques_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_ques_arg_/_ques_arg_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_read_/_read_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_s_e_/_s_e_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_sed_/_sed_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_s_s_/_s_s_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_s_t_/_s_t_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_stack_nm_/_stack_nm_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_tag_nm_/_tag_nm_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_test_/_test_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_unix_/_unix_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_unix_/_unix_/_man/utils_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_vim_/_vim_/_man/man_1.man
${COMMUNIS_PATH}/Deploy_store/.qa/main_repo_fn/dir_zz_/_zz_/_man/man_1.man
