#!/bin/bash

#. "$HOME/.bashrc"

filename="${COMMUNIS_PATH}/.git/hooks/pre-push"

echo -e "${HLIGHT}---start file: $filename---${NORMAL}" # start file

# ${COMMUNIS_PATH}

#------------------------------------------------------
#----------------------------
#----------

. "${COMMUNIS_PATH}/Deploy_store/.qa/sis_apps/sis_git.2/git_pre_push_fns.sh"

git_pre_push_bck_hooks

#----------
#----------------------------
#------------------------------------------------------
unset filename

exit 0
