#!/bin/bash

#. "$HOME/.bashrc"

filename="$PATH_FN/dir_00000/_00000/_sh/tag_00000.sh"

echo -e "${HLIGHT}---start file: $filename---${NORMAL}" # start file

#e_exer "Questions? See far!" "$filename" "$LINENO"

#up_lib_git ${FUNCNAME[0]}

tag_00000(){
    echo -e "${CYAN}---${FUNCNAME[0]}() $*---${NORMAL}" #started functions
    less $PATH_FN/dir_00000/_00000/_config/mane_00000.tag
}

unset filename