#!/bin/bash

#. "$HOME/.bashrc"

filename="$PATH_FN/dir_00000/_00000/_sh/add_tag_00000.sh"

echo -e "${HLIGHT}---start file: $filename---${NORMAL}" # start file

#e_exer "Questions? See far!" "$filename" "$LINENO"

#up_lib_git ${FUNCNAME[0]}

add_tag_00000(){
    echo -e "${CYAN}---${FUNCNAME[0]}() $*---${NORMAL}" #started functions
    
    unset _choice_tag_
    choice_tag
    
    f_tag=$_choice_tag_
    unset _choice_tag_
    
    # unset _choice_tag_file_
    # choice_tag_file "$PATH_TAG"
    # full_path=$_choice_tag_file_
    
    # echo -e "${GREEN}\$full_path = $full_path${NORMAL}" #print variable
    
    # unset _f2a_
    
    # f2a "$_choice_tag_file_"
    # echo -e "${GREEN}\${_f2a_[@]} = ${_f2a_[*]}${NORMAL}" #print variable
    
    # unset _choice_tag_file_
    
    # PS3="eligendi actiones: "
    
    # unset tag
    # select tag in "${_f2a_[@]}";do
    
    #     adds=$tag
    #     break
    
    # done
    # unset tag
    
    # echo -e "${GREEN}\$adds = $adds${NORMAL}" #print variable
    # echo -e "${GREEN}\$PATH_TAG = $PATH_TAG${NORMAL}" #print variable
    
    # f_tag=$(echo "$full_path/$adds" | sed 's|'$PATH_TAG'||')
    # echo -e "${GREEN}\$f_tag = $f_tag${NORMAL}" #print variable
    
    unset _f2a_
    f2a "$PATH_FN/dir_00000/_00000/_config/mane_00000.tag"
    
    echo -e "${GREEN}\$adds = $adds${NORMAL}" #print variable
    echo -e "${GREEN}\${_f2a_[@]} = ${_f2a_[*]}${NORMAL}" #print variable
    
    unset flag
    
    unset item
    for item in "${_f2a_[@]}" ; do
        
        if [ $item = $f_tag ];then
            # qq_pause "${BLUE}---$adds allready in tags---${NORMAL}"
            flag="false"
            break
        fi
    done
    unset item
    unset _f2a_
    
    if [ -z $flag ];then
        echo -e "${BLUE}---NOT Found---${NORMAL}" #sistem info mesage
        qq_pause "${BLUE}---$f_tag add to tags mane_00000.tag?---${NORMAL}"
        
        if_f_h "$PATH_FN/dir_00000/_00000/_config/mane_00000.tag"
        echo "$f_tag" >> "$PATH_FN/dir_00000/_00000/_config/mane_00000.tag"
    else
        echo -e "${BLUE}---find---${NORMAL}" #sistem info mesage
        qq_pause "${BLUE}---$f_tag  allready in tags---${NORMAL}"
        echo "bye)))"
    fi
    # echo "$adds" > "$PATH_FN/dir_00000/_00000/_config/mane_00000.tag"
    
    
    unset _f2a_
    
    # less $PATH_FN/dir_00000/_00000/_config/mane_00000.tag
}

unset filename