#!/bin/bash

#. "/home/st/.bashrc"

filename="${PATH_MAIN_REPO_FN_DIR}/dir_00000/_00000/_sh/magic_00000.sh"

echo -e "${HLIGHT}---start file: $filename---${NORMAL}" # start file

#e_exer "Questions? See far!" "$filename" "$LINENO"

magic_00000(){
    echo -e "${CYAN}---${FUNCNAME[0]}() $*---${NORMAL}" #started functions
    
    arr=()
    arr+=("start")
    arr+=("edit")
    arr+=("vim")
    arr+=("man")
    arr+=("menu")
    arr+=("tag")
    arr+=("add_tag")
    # arr+=("add_free_tag")
    # arr+=("vim")
    # arr+=("vim")
    
    
    # arr+=("ls -a - отображать все файлы, включая скрытые")
    # res+=("ls -a $*")
    # arr+=("ls -a - отображать все файлы, включая скрытые")
    # res+=("ls -a $*")
    # arr+=("ls -a - отображать все файлы, включая скрытые")
    # res+=("ls -a $*")
    # arr+=("ls -a - отображать все файлы, включая скрытые")
    # res+=("ls -a $*")
    
    PS3="eligendi actiones: "
    
    select item in "${arr[@]}";do
        
        dilectus=$item
        break
        
    done
    
    case $dilectus in
        
        "start")
            echo -e "${CYAN}---start mode---${NORMAL}" #started functions
            qq_pause "Start jj_ far enter params"
            echo "enter all params:"
            read -r params
            00000 $params
            
        ;;
        
        "edit")
            echo -e "${CYAN}---vim mode---${NORMAL}" #started functions
            if_d_s "${PATH_MAIN_REPO_FN_DIR}/_config/agno_tag"
            qq_pause "WARN not delete!!!Only add file and dir"
            gvim -v "${PATH_MAIN_REPO_FN_DIR}/_config/agno_tag"
            magic_00000 @
            
        ;;
        
        "vim")
            echo -e "${CYAN}---vim mode---${NORMAL}" #started functions
            if_d_s "$ORIGO_DIR"
            gvim -v "$ORIGO_DIR"
            magic_00000 @
            
        ;;
        
        "man")
            echo -e "${CYAN}---man mode---${NORMAL}" #started functions
            if_d_s "$ORIGO_DIR"/_$FNN/_man
            man_is "$ORIGO_DIR"/_$FNN/_man
            magic_00000 @
            
        ;;
        
        "menu")
            echo -e "${CYAN}---menu mode---${NORMAL}" #started functions
            if_f_h "$ORIGO_DIR/_$FNN/_sh/menu_$FNN.sh"
            . "$ORIGO_DIR/_$FNN/_sh/menu_$FNN.sh"
            menu_$FNN
            magic_00000 @
        ;;
        
        "tag")
            echo -e "${CYAN}---${res[3]}---${NORMAL}" #started functions
            tag_00000
            magic_00000 @
        ;;
        
        "add_tag")
            echo -e "${CYAN}---${res[3]}---${NORMAL}" #started functions
            add_tag_00000
            magic_00000 @
        ;;
        
        # "add_free_tag")
        #     echo -e "${CYAN}---${res[3]}---${NORMAL}" #started functions
        #     add_free_tag_00000
        #     magic_00000 @
        # ;;
        
        # "${arr[3]}")
        #     echo -e "${CYAN}---${res[3]}---${NORMAL}" #started functions
        #     ${res[3]}
        # ;;
        
        *)
            echo -e "${BLUE}---main mode---${NORMAL}" #sistem info mesage
        ;;
        
    esac
    
}

#up_lib_git ${FUNCNAME[0]}

unset filename