#!/bin/bash

#! debag
# . "$HOME/.bashrc"
#!

filename="{rts_fn}/dir_00000/00000.sh"

echo -e "${HLIGHT}--- start file: $filename with args: $@ ---${NORMAL}" # start file

#e_exer "Questions? See far!" "$filename" "$LINENO"

#up_lib_git

00000() {

    #{def_const_reciver}

    #{ctrl_args_reciver}

    #{init_body_reciver}

}

# 00000 @

unset filename
